messages:
  # Заражение игрока командой /disease infect
  # Принимает <player> тег
  infect-player: "<player> is successfully infected."

  # Излечение игрока командой /disease cure
  # Принимает <player> тег
  cure-player: "<player> is successfully cured."

  # Сообщение излеченному игроку
  # Принимает <player> тег
  cured: "You were cured by come reason."

  # Сообщение игроку, зараженному ударом эндермена
  #infected-by-endermanHit: "You were infected by an enderman hit."

  # Сообщение игроку, зараженному смертью он эндермена
  #infected-by-endermanKilling: "You were infected by an enderman kill."

  # Сообщение игроку, зараженному другим игроком
  #infected-by-player: "You were infected by nearby player."

  # Сообщение зараженному командой /disease infect игроку
  #infected-by-staff: "You were infected by a staff."

  # Сообщение игроку, который был заражен
  # Принимает <player> тег
  infected: "You were infected for some reason."

  # Если игрок уже заражен
  # Принимает <player> тег
  already-infected: "<player> is already infected."

  # Если игрок не болен
  # Принимает <player> тег
  not-infected: "<player> is not infected."

  # Сообщение при пустом списке зараженных игроков
  noOne-infected: "Currently no one is infected."

  # Не указан игрок для выполнения команды
  no-target: "You doesn't provide any player to execute command."

  # Неправильно указан ник цели
  # Принимает <player> тег
  noSuch-player: "Don't found any player with name <player>"

  # Пример выполнения /disease cure
  example-cure: "Example: /disease cure Tanos"

  # Примервыполнения /disease infect
  example-infect: "Example: /disease infect Gaben"

  # Сообщение о болезни
  disease: "You are ill..."

  # Если проверенный предметом игрок заражен
  # Принимает <player> тег
  checkedPlayer-isInfected: "<player> is infected."

  # Если проверенный предметов игрок здоров
  # Принимает <player> тег
  checkedPlayer-notInfected: "<player> is not infected."

  no-permission: "<dark_red>No permission to execute command</dark_red>"

chances:
  # Шанс быть зараженным от удара эндермена
  infect-by-hitting: 5

  # Шанс быть зараженным после смерти от эндермена
  infect-by-death: 50

  # Шанс быть зараженным от другого игрока
  infect-by-player: 10

  # Шанс получить сообщение о заражении раз в 10 сек (изменяется в schedulers-delay)
  get-diseaseMessage: 5

  # Шанс получить дебаф от заражения раз в 10 сек (изменяется в schedulers-delay)
  get-debuffChance: 5

utils:
  # Радиус возможного распространения заражения на игроков
  infect-radius: 20

  # Задержка в секундах
  schedulers-delay: 10

  # Названия предметов, блокирующих заражение игроками
  maskItems-names:
    - Маска
    - Респиратор
    - Противогаз

  # ID кастомного ItemModel предмета для проверки здоровья
  checkItem-customModel: 1

  # Material предмета проверки здоровья
  checkItem-type: STONE

  # Название для выдачи предмета проверки здоровья
  checkItem-name: "Disease Checker"

  # Длительность эффекта тошноты при заражении (рандом от и до)

  # ОТ
  confusionDuration-origin: 3
  # ДО
  confusionDuration-bound: 10